<<<<<<< HEAD
CREATE TABLE scott.supplier (
  supplier_id numeric(10) not null,
  supplier_name varchar2(50) not null,
  contact_name varchar2(50),
  CONSTRAINT supplier_pk PRIMARY KEY (supplier_id)
);

SET LINES 150 PAGES 5000 TIMING ON;
COL CONSTRAINT_NAME FOR A40;
COL INDEX_NAME FOR A40;
COL STATUS FOR A10;
COL TABLE_NAME FOR A25;

SELECT OWNER||'.'||CONSTRAINT_NAME CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, STATUS, INDEX_OWNER||'.'||INDEX_NAME INDEX_NAME
FROM DBA_CONSTRAINTS WHERE OWNER='SCOTT' AND TABLE_NAME='SUPPLIER' ORDER BY 1;

ALTER TABLE SCOTT.SUPPLIER RENAME CONSTRAINT SUPPLIER_PK TO PK_SUPPLIER;

ALTER TABLE SCOTT.SUPPLIER DROP CONSTRAINT PK_SUPPLIER;

=======
CREATE TABLE scott.supplier (
  supplier_id numeric(10) not null,
  supplier_name varchar2(50) not null,
  contact_name varchar2(50),
  CONSTRAINT supplier_pk PRIMARY KEY (supplier_id)
);

SET LINES 150 PAGES 5000 TIMING ON;
COL CONSTRAINT_NAME FOR A40;
COL INDEX_NAME FOR A40;
COL STATUS FOR A10;
COL TABLE_NAME FOR A25;

SELECT OWNER||'.'||CONSTRAINT_NAME CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, STATUS, INDEX_OWNER||'.'||INDEX_NAME INDEX_NAME
FROM DBA_CONSTRAINTS WHERE OWNER='SCOTT' AND TABLE_NAME='SUPPLIER' ORDER BY 1;

ALTER TABLE SCOTT.SUPPLIER RENAME CONSTRAINT SUPPLIER_PK TO PK_SUPPLIER;

ALTER TABLE SCOTT.SUPPLIER DROP CONSTRAINT PK_SUPPLIER;

>>>>>>> 327b5e2c2d7f1e6078f5d0c4cff716a75d749ca2
ALTER TABLE SCOTT.SUPPLIER ADD CONSTRAINT supplier_pk PRIMARY KEY (supplier_id);