<<<<<<< HEAD
ALTER SESSION SET NLS_DATE_FORMAT='DD-Mon-RR HH24:MI:SS';
SELECT LAST_UPDATE_DATE,RELEASE_NAME FROM APPS.FND_PRODUCT_GROUPS;

=======
ALTER SESSION SET NLS_DATE_FORMAT='DD-Mon-RR HH24:MI:SS';
SELECT LAST_UPDATE_DATE,RELEASE_NAME FROM APPS.FND_PRODUCT_GROUPS;

>>>>>>> 327b5e2c2d7f1e6078f5d0c4cff716a75d749ca2
Location of portpool.lst file: $INST_TOP/admin/out/portpool.lst