-- NAME: gapl.sql
-- LAST UPDATED: 16 September 2021
-- USAGE: @gapl
-- DISCLAIMER:
--  This script is free and provided by azizpw (PT Metrodata Electronics, Tbk.) for all customers who use Oracle Data Guard (Logical Standby).
SET LINES 250 PAGES 5000 TIMING ON TRIM ON;
--Check DB information
COL PLATFORM_NAME FOR A30;
COL DB_UNIQUE_NAME FOR A15;
COL CURRENT_SCN FOR A20;
COL HOST_NAME FOR A30;
SELECT NAME,DB_UNIQUE_NAME,INSTANCE_NAME,DBID,HOST_NAME,PLATFORM_NAME,OPEN_MODE,STATUS,LOG_MODE,DATABASE_ROLE,TO_CHAR(CURRENT_SCN)CURRENT_SCN FROM V$DATABASE X,V$INSTANCE Y;
ALTER SESSION SET NLS_DATE_FORMAT='DD-MON-RR HH24:MI:SS';
--Check gap on Logical Standby
SELECT LATEST_TIME,APPLIED_TIME,MINING_TIME, (LATEST_TIME-APPLIED_TIME)*24*3600 GAP_IN_SECOND FROM V$LOGSTDBY_PROGRESS;
SELECT A.SEQUENCE_RECEIVED,A.THREAD,B.SEQUENCE_APPLIED,B.THREAD FROM (SELECT MAX(SEQUENCE#) SEQUENCE_RECEIVED,THREAD# THREAD FROM DBA_LOGSTDBY_LOG GROUP BY THREAD#) A,
(SELECT MAX(SEQUENCE#) SEQUENCE_APPLIED,THREAD# THREAD FROM DBA_LOGSTDBY_LOG WHERE APPLIED='YES' GROUP BY THREAD#) B WHERE A.THREAD=B.THREAD;