<<<<<<< HEAD
SET LINES 150 PAGES 5000 TIMING ON ECHO ON
SPOOL D:\GatherSCOTT.log
SELECT TO_CHAR(SYSDATE,'DD-Mon-RR HH24:MI:SS')MULAI FROM DUAL;
EXEC DBMS_STATS.GATHER_TABLE_STATS('SCOTT', 'BONUS', ESTIMATE_PERCENT => DBMS_STATS.AUTO_SAMPLE_SIZE, CASCADE => TRUE);
EXEC DBMS_STATS.GATHER_TABLE_STATS('SCOTT', 'DEPT', ESTIMATE_PERCENT => DBMS_STATS.AUTO_SAMPLE_SIZE, CASCADE => TRUE);
EXEC DBMS_STATS.GATHER_TABLE_STATS('SCOTT', 'EMP', ESTIMATE_PERCENT => DBMS_STATS.AUTO_SAMPLE_SIZE, CASCADE => TRUE);
EXEC DBMS_STATS.GATHER_TABLE_STATS('SCOTT', 'SALGRADE', ESTIMATE_PERCENT => DBMS_STATS.AUTO_SAMPLE_SIZE, CASCADE => TRUE);
SELECT TO_CHAR(SYSDATE,'DD-Mon-RR HH24:MI:SS')SELESAI FROM DUAL;
SPOOL OFF;
EXIT;
=======
SET LINES 150 PAGES 5000 TIMING ON ECHO ON
SPOOL D:\GatherSCOTT.log
SELECT TO_CHAR(SYSDATE,'DD-Mon-RR HH24:MI:SS')MULAI FROM DUAL;
EXEC DBMS_STATS.GATHER_TABLE_STATS('SCOTT', 'BONUS', ESTIMATE_PERCENT => DBMS_STATS.AUTO_SAMPLE_SIZE, CASCADE => TRUE);
EXEC DBMS_STATS.GATHER_TABLE_STATS('SCOTT', 'DEPT', ESTIMATE_PERCENT => DBMS_STATS.AUTO_SAMPLE_SIZE, CASCADE => TRUE);
EXEC DBMS_STATS.GATHER_TABLE_STATS('SCOTT', 'EMP', ESTIMATE_PERCENT => DBMS_STATS.AUTO_SAMPLE_SIZE, CASCADE => TRUE);
EXEC DBMS_STATS.GATHER_TABLE_STATS('SCOTT', 'SALGRADE', ESTIMATE_PERCENT => DBMS_STATS.AUTO_SAMPLE_SIZE, CASCADE => TRUE);
SELECT TO_CHAR(SYSDATE,'DD-Mon-RR HH24:MI:SS')SELESAI FROM DUAL;
SPOOL OFF;
EXIT;
>>>>>>> 327b5e2c2d7f1e6078f5d0c4cff716a75d749ca2
