<<<<<<< HEAD
CONN / AS SYSDBA
GRANT CREATE ANY SQL PROFILE TO APPS;
GRANT ALTER ANY SQL PROFILE TO APPS;
GRANT DROP ANY SQL PROFILE TO APPS;
GRANT ADMINISTER ANY SQL TUNING SET TO APPS;
GRANT ADVISOR TO APPS;
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO APPS;
CONN APPS/APPS;
=======
CONN / AS SYSDBA
GRANT CREATE ANY SQL PROFILE TO APPS;
GRANT ALTER ANY SQL PROFILE TO APPS;
GRANT DROP ANY SQL PROFILE TO APPS;
GRANT ADMINISTER ANY SQL TUNING SET TO APPS;
GRANT ADVISOR TO APPS;
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO APPS;
CONN APPS/APPS;
>>>>>>> 327b5e2c2d7f1e6078f5d0c4cff716a75d749ca2
SHO USER;