<<<<<<< HEAD
SET LINES 200 PAGES 5000;
COL OBJNAME FORMAT A60;
SELECT COUNT(1)INV_OBJ FROM DBA_OBJECTS WHERE STATUS = 'INVALID';
SELECT /*+PARALLEL(8)*/OWNER||'.'||OBJECT_NAME OBJNAME, OBJECT_TYPE OBJTYPE FROM DBA_OBJECTS WHERE STATUS='INVALID' ORDER BY 1;
=======
SET LINES 200 PAGES 5000;
COL OBJNAME FORMAT A60;
SELECT COUNT(1)INV_OBJ FROM DBA_OBJECTS WHERE STATUS = 'INVALID';
SELECT /*+PARALLEL(8)*/OWNER||'.'||OBJECT_NAME OBJNAME, OBJECT_TYPE OBJTYPE FROM DBA_OBJECTS WHERE STATUS='INVALID' ORDER BY 1;
>>>>>>> 327b5e2c2d7f1e6078f5d0c4cff716a75d749ca2
