set lines 250 pages 5000;
--Redo log information
COL MEMBER FOR A100;
--SELECT * FROM V$LOGFILE ORDER BY 1,3,4;
COL STATUS FOR A15;
--SELECT GROUP#, THREAD#, SEQUENCE#, ROUND((BYTES/1024/1024),2)REDO_MB, MEMBERS, ARCHIVED, STATUS, FIRST_CHANGE# FROM V$LOG ORDER BY 1;
--SELECT X.GROUP#, X.THREAD#, X.SEQUENCE#, ROUND((X.BYTES/1024/1024),2)REDO_MB, X.MEMBERS, X.ARCHIVED, X.STATUS, Y.TYPE, Y.MEMBER FROM V$LOG X JOIN V$LOGFILE Y ON X.GROUP#=Y.GROUP# ORDER BY 1,2,3;
--SELECT GROUP#, THREAD#, SEQUENCE#, ROUND((BYTES/1024/1024),2)REDO_MB, ARCHIVED, STATUS, FIRST_CHANGE# FROM V$STANDBY_LOG ORDER BY 1;
SELECT X.GROUP#, X.THREAD#, X.SEQUENCE#, ROUND((X.BYTES/1024/1024),2)REDO_MB, X.ARCHIVED, X.STATUS, Y.TYPE, Y.MEMBER FROM V$STANDBY_LOG X JOIN V$LOGFILE Y ON X.GROUP#=Y.GROUP#
UNION ALL SELECT X.GROUP#, X.THREAD#, X.SEQUENCE#, ROUND((X.BYTES/1024/1024),2)REDO_MB, X.ARCHIVED, X.STATUS, Y.TYPE, Y.MEMBER FROM V$LOG X JOIN V$LOGFILE Y ON X.GROUP#=Y.GROUP# ORDER BY 1,2,3;