SET LINES 200 PAGES 5000 TIMING ON;
COL ACTION_TIME FOR A30;
COL ACTION FOR A10;
COL NAMESPACE FOR A10;
COL VERSION FOR A25;
COL ID FOR 99;
COL BUNDLE_SERIES FOR A15;
COL COMMENTS FOR A80;
SELECT * FROM REGISTRY$HISTORY ORDER BY 1 DESC;
SELECT BANNER FROM V$VERSION;

COL COMP_NAME FOR A35;
SELECT COMP_ID,COMP_NAME,VERSION_FULL,STATUS FROM DBA_REGISTRY ORDER BY 1;